Add-Type -AssemblyName System.Drawing
$assetDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$bitmap = [System.Drawing.Bitmap]::new(256, 256)
$graphics = [System.Drawing.Graphics]::FromImage($bitmap)
$graphics.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::AntiAlias
$graphics.Clear([System.Drawing.Color]::FromArgb(19, 21, 23))
$brush = [System.Drawing.SolidBrush]::new([System.Drawing.Color]::FromArgb(245, 202, 67))
$font = [System.Drawing.Font]::new('Segoe UI', 191, [System.Drawing.FontStyle]::Bold, [System.Drawing.GraphicsUnit]::Pixel)
$format = [System.Drawing.StringFormat]::new()
$format.Alignment = [System.Drawing.StringAlignment]::Center
$format.LineAlignment = [System.Drawing.StringAlignment]::Center
$graphics.DrawString('C', $font, $brush, [System.Drawing.RectangleF]::new(0, -11, 256, 256), $format)
$pngPath = Join-Path $assetDir 'clutchub.png'
$icoPath = Join-Path $assetDir 'clutchub.ico'
$bitmap.Save($pngPath, [System.Drawing.Imaging.ImageFormat]::Png)
$graphics.Dispose()
$font.Dispose()
$brush.Dispose()
$format.Dispose()
$pixelRect = [System.Drawing.Rectangle]::new(0, 0, 256, 256)
$pixelData = $bitmap.LockBits($pixelRect, [System.Drawing.Imaging.ImageLockMode]::ReadOnly, [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
$pixels = [byte[]]::new([Math]::Abs($pixelData.Stride) * 256)
[System.Runtime.InteropServices.Marshal]::Copy($pixelData.Scan0, $pixels, 0, $pixels.Length)
$bitmap.UnlockBits($pixelData)
$bitmap.Dispose()
$dibStream = [System.IO.MemoryStream]::new()
$dib = [System.IO.BinaryWriter]::new($dibStream)
$dib.Write([uint32]40)
$dib.Write([int32]256)
$dib.Write([int32]512)
$dib.Write([uint16]1)
$dib.Write([uint16]32)
$dib.Write([uint32]0)
$dib.Write([uint32](256 * 256 * 4))
foreach ($unused in 1..4) { $dib.Write([uint32]0) }
for ($row = 255; $row -ge 0; $row--) { $dib.Write($pixels, $row * 256 * 4, 256 * 4) }
$dib.Write([byte[]]::new(256 * 32))
$dib.Flush()
$bytes = $dibStream.ToArray()
$dib.Dispose()
$stream = [System.IO.File]::Create($icoPath)
$writer = [System.IO.BinaryWriter]::new($stream)
$writer.Write([uint16]0)
$writer.Write([uint16]1)
$writer.Write([uint16]1)
$writer.Write([byte]0)
$writer.Write([byte]0)
$writer.Write([byte]0)
$writer.Write([byte]0)
$writer.Write([uint16]1)
$writer.Write([uint16]32)
$writer.Write([uint32]$bytes.Length)
$writer.Write([uint32]22)
$writer.Write($bytes)
$writer.Dispose()
